### ISSUE TITLE
Not displaying the module

### ISSUE THREAD

**Issue by amir-barkhordary** [Nikba-Creative-Studio/Sales-Dashboard-WHMCS-Module#1]
hello
Thank you for your effort.
I aim to test your module
But after uploading, this module is not displayed in my plugins list.
Does it need to create a hook.php file?

**Comment by Nikba-Creative-Studio** [comment]
To activate the module, please follow these steps:

1. Upload Module:

Upload the sales_dashboard directory to your WHMCS installation's modules/addons/ directory.

2. Activate Module:

Navigate to WHMCS Admin Area > Setup > Addon Modules.
Locate "Sales Dashboard" in the list and click Activate.

3. Configure Module:

After activation, click on Configure next to the Sales Dashboard module.
Enable the module by selecting Yes under "Enable the Sales Dashboard module."
Under "Access Control," select your desired access level.

<img width="100%" alt="Screenshot 2024-09-02 at 10 49 24" src="https://github.com/user-attachments/assets/e3ff28e0-2a4d-48f8-a614-69536dcc8a96">


4. Access Module:

You can access the Sales Dashboard from the WHMCS admin sidebar under "Sales Dashboard."

<img width="315" alt="Screenshot 2024-09-02 at 10 49 51" src="https://github.com/user-attachments/assets/412ad291-d55e-406c-a44a-2315409b7037">
